## LINEAR ALGEBRA PROBLEMS


## Basic Matrix Operations

1.Matrix Operation Perform the following operations on the given matrices: A=[[2 -1], [​0 3​]] B=[[1 ​ 2], [-3 4​]] a. A+B b. AB c. 3A−2B

In [1]:
import numpy as np

In [2]:
A = np.array([[2, -1],
              [0,  3]])

B = np.array([[ 1,  2],
              [-3,  4]])

In [3]:
#additon of array A and B i.e A+B
c = A + B
print(c)

[[ 3  1]
 [-3  7]]


In [4]:
#multication of A and B i.e A*B
AB = A @ B
print(AB)

[[ 5  0]
 [-9 12]]


In [5]:
#3A−2B
result = 3*A - 2*B
result

array([[ 4, -7],
       [ 6,  1]])

## DETERMINANT

In [6]:
import numpy.linalg as LA

In [7]:
det_A = LA.det(A)
print(det_A)

6.0


In [8]:
#since determinant is 6 meaning its inverse exist so
A_inv = LA.inv(A)
print(A_inv)

[[0.5        0.16666667]
 [0.         0.33333333]]


## Eigenvalues and Eigenvectors

In [9]:
C = np.array([[ 4,  1],
              [-2,  1]])

eigenvalues, eigenvectors = LA.eig(C)


lambda1 = eigenvalues[0]
lambda2 = eigenvalues[1]

print(lambda1, lambda2)

print("eigen vectors for ",lambda1)
v1 = eigenvectors[:, 0]
print(v1)

v2= eigenvectors[ :, 1]
print("eigen vectors for ",lambda2)
print(v2)

3.0 2.0
eigen vectors for  3.0
[ 0.70710678 -0.70710678]
eigen vectors for  2.0
[-0.4472136   0.89442719]


4.You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3) car 1: x1: 4 x2: 1.5 x3: 100 and price: 20
car 2: x1: 6 x2: 2.0 x3: 150 and price: 30

Then, find the price of a car 3 with features x1: 8 x2: 3.0 x3: 200 price:?

Hints:

1.Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector
2.Compute β (the coefficients) using the normal equation: β=(X.T * X)^−1 X.T y
where, X.T --> transpose matrix

In [10]:
X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])

y = np.array([[20],
              [30]])

XT_X = X.T @ X
print(XT_X)
G=LA.det(XT_X)
print("DETERMINANT is=",G)

[[5.20e+01 1.80e+01 1.30e+03]
 [1.80e+01 6.25e+00 4.50e+02]
 [1.30e+03 4.50e+02 3.25e+04]]
DETERMINANT is= 0.0


-Determinant is 0

(XᵀX) is not invertible
Price of car 3 cannot be uniquely predicted

In [11]:
#pinv is pseudo-inverse which is done when a normal matrix inverse does not exist
beta_pinv = LA.pinv(X) @ y
print(beta_pinv)

x3 = np.array([[8, 3.0, 200]])
price_car3 = x3 @ beta_pinv
print("price of car",price_car3)

[[7.98722045e-03]
 [2.84217094e-14]
 [1.99680511e-01]]
price of car [[40.]]
